### ISSUE TITLE
Command failed, but works via termin

### ISSUE THREAD

**Issue by mukuls-brdsys** [wubzz/pdf-merge#12]
I am getting the following error
Error: Command failed: /usr/bin/pdftk '/home/user/Desktop/reports/routes/../merging/2017-03-16T05:38:13.554Z.pdf' cat output /tmp/tmp-4501zXim6Nm8BY3y
Error: Unable to find file.
Error: Failed to open PDF file: 
   '/home/brds4/Desktop/reports/routes/../merging/2017-03-16T05:38:13.554Z.pdf'
Errors encountered.  No output created.
Done.  Input errors, so no output created.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

But if I execute the same command in terminal it's working fine.

**Comment by mukuls-brdsys** [comment]
This happens if pdftk path is set manually, It should be documented that pdftk path is not required for linux.
